Jonah/2600 update dev dependencies to latest
DataBiosphere/data-portal pull request #2603
Opened 2024-12-06 00:40 UTC by jpaten

draft pr so that commit checks run

2024-12-06 01:57 UTC, jpaten commented
Running list of changes
- sonar
  - noopener error
  - todo warn
  - redundant type alias warn
- prettier
  - es5 commas
  - commas in arrow brackets `<>` that run onto multiple pages
- remark-gfm
  - Gives prerender error on certain mdx pages when built, uncertain why this happens but doesn't seem to cause any issues when rendered

2024-12-07 04:58 UTC, hunterckx requested changes

2024-12-07 04:58 UTC, hunterckx commented on package.json
> +    "@types/node": "^22.10.1",
`@types/node` should be matched with the Node version, so I think this should stay at `^20.10.0` (and I believe this is a convention for other type packages, so we might want to keep some of the others the same as well)

2024-12-07 06:52 UTC, jpaten commented
@hunterckx I updated the types dependencies to match the version of the corresponding prod dependency, or to the version they were at originally if there is there isn't a version of the type dependency that's the same as the prod dependency. Let me know if that works, I can also just change them to be the exact same as they were originally

2024-12-07 22:29 UTC, hunterckx approved these changes
Looks good!

2024-12-07 22:30 UTC, merged