Added Trufflehog
DataBiosphere/data-portal pull request #428
Opened 2019-05-07 22:32 UTC by GPelayo

2019-05-09 01:25 UTC, hannes-ucsc requested changes
And just to confirm, you mentioned that Trufflehog actually found a secret in the code base? Why isn't that being detected in https://allspark.dev.data.humancellatlas.org/HumanCellAtlas/data-portal/-/jobs/29602 where the `echo` was absent?

2019-05-09 01:25 UTC, hannes-ucsc commented on .gitlab-ci.lower-env.yml
> +    - echo pip install trufflehog
```suggestion
    - pip install trufflehog
```

2019-05-09 01:25 UTC, hannes-ucsc commented on .gitlab-ci.lower-env.yml
> +    - echo trufflehog --regex --rules trufflehog-rules.json --branch develop --entropy=False --max_depth 30 https://github.com/HumanCellAtlas/data-portal.git
```suggestion
    - trufflehog --regex --rules trufflehog-rules.json --branch develop --entropy=False --max_depth 30 https://github.com/HumanCellAtlas/data-portal.git
```

2019-05-09 16:51 UTC, GPelayo commented
I probably meant the data-browser codebase. The data-portal didn't contain any secrets.

2019-05-09 17:48 UTC, hannes-ucsc commented
@GPelayo, please Slack (!) me the commit and location of that secret.

2019-05-11 07:33 UTC, hannes-ucsc approved these changes

2019-05-16 17:13 UTC, merged